version: '3.8'

services:
  redis:
    image: redis:latest
    hostname: redis
    restart: unless-stopped
    expose:
      - "6379"
  
  webapp:
    image: webapp:latest
    hostname: webapp
    restart: unless-stopped
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://localhost/
    ports:
      - "5000:5000"
    depends_on: 
      - redis
